//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medikament
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedikamentEntities9 : DbContext
    {
        public MedikamentEntities9()
            : base("name=MedikamentEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ВидМедикамента> ВидМедикамента { get; set; }
        public virtual DbSet<ДокументПоставкии> ДокументПоставкии { get; set; }
        public virtual DbSet<ДокументСписания> ДокументСписания { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Измерение> Измерение { get; set; }
        public virtual DbSet<Медикамент> Медикамент { get; set; }
        public virtual DbSet<Поставка> Поставка { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Склады> Склады { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<СписокСписания> СписокСписания { get; set; }
    }
}
