//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medikament
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДокументСписания
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ДокументСписания()
        {
            this.СписокСписания = new HashSet<СписокСписания>();
        }
    
        public int КодДокументаСписания { get; set; }
        public string Комментарий { get; set; }
        public Nullable<int> КодСотрудника { get; set; }
        public Nullable<System.DateTime> ДатаСписания { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокСписания> СписокСписания { get; set; }
    }
}
