//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medikament
{
    using System;
    using System.Collections.Generic;
    
    public partial class Медикамент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Медикамент()
        {
            this.Склад = new HashSet<Склад>();
        }
    
        public int КодМедикамента { get; set; }
        public string НаименованиеМедикамента { get; set; }
        public Nullable<int> КодВидаМедикамента { get; set; }
        public Nullable<int> КодИзмерения { get; set; }
        public Nullable<int> КоличествоВУпаковке { get; set; }
        public string СрокГодности { get; set; }
    
        public virtual ВидМедикамента ВидМедикамента { get; set; }
        public virtual Измерение Измерение { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Склад> Склад { get; set; }
    }
}
