//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medikament
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокСписания
    {
        public int КодСписания { get; set; }
        public Nullable<int> КодДокументаСписания { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> КодПозицииСклада { get; set; }
    
        public virtual ДокументСписания ДокументСписания { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
